[package]
name = "chuangshi-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tonic.workspace = true
prost.workspace = true
bytes.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true

[build-dependencies]
tonic-build = "0.11"